version: "3"
services:
  snapcraft:
    image: snapcore/snapcraft
    volumes:
      - .:/build
    working_dir: /build
    command: bash -c "apt update && apt upgrade --yes && apt autoremove --yes && apt autoclean --yes && snapcraft"
